name: CI
# Se ejecuta en cada push y pull request a las ramas principales
on:
push:
branches: [main]
pull_request:
branches: [main]
jobs:
lint:
name: Lint Code
runs-on: ubuntu-latest
strategy:
matrix:
node-version: [20.x] # Prueba en Node.js version 20
steps:
# 1. Checkout del código fuente
- name: Checkout repository
uses: actions/checkout@v3
# 2. Configurar la versión de Node.js
- name: Setup Node.js ${{ matrix.node-version }}
uses: actions/setup-node@v3
with:
node-version: ${{ matrix.node-version }}
cache: "npm" # Habilita el caché de npm para acelerar las instalaciones
# 3. Instalar dependencias
- name: Install dependencies
run: npm install
# 4. Ejecutar ESLint para verificar el código
- name: Run ESLint
run: npm run lint
build:
name: Build Project
runs-on: ubuntu-latest
needs: lint # Este job solo se ejecuta si el job 'lint' es exitoso
strategy:
matrix:
node-version: [20.x] # Asegura que el build se pruebe en las mismas versiones de
Node.js
steps:
# 1. Checkout del código fuente
- name: Checkout repository
uses: actions/checkout@v3
# 2. Configurar la versión de Node.js
- name: Setup Node.js ${{ matrix.node-version }}
uses: actions/setup-node@v3
with:
node-version: ${{ matrix.node-version }}
cache: "npm"
# 3. Instalar dependencias
- name: Install dependencies
run: npm install
# 4. Compilar el proyecto TypeScript
- name: Build project
run: npm run build
